# Introduction to NumPy and pandas

This notebook introduces:

- NumPy arrays
- pandas Series and DataFrames
- Indexing and slicing
- The colon syntax, including `[:30]`, `[10:20]`, `[::2]`, and `[::-1]`
- Selecting rows and columns with `.loc[]` and `.iloc[]`
- Filtering data with conditions

The notebook is intended for beginners. Students should run each cell in order and change the examples to test their understanding.

## 1. Importing the libraries

NumPy is normally imported as `np`, while pandas is normally imported as `pd`.

In [1]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("pandas version:", pd.__version__)

NumPy version: 2.4.6
pandas version: 3.0.3


# Part A — Basic NumPy

## 2. Creating NumPy arrays

A NumPy array is an ordered collection of values. Unlike a standard Python list, it supports efficient mathematical operations.

In [2]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(type(numbers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


Arrays can also be created using functions such as:

- `np.arange(start, stop, step)`
- `np.zeros(size)`
- `np.ones(size)`
- `np.linspace(start, stop, number_of_values)`

In [3]:
a = np.arange(0, 10)
b = np.arange(0, 20, 2)
c = np.zeros(5)
d = np.ones(5)
e = np.linspace(0, 1, 6)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2 3 4 5 6 7 8 9]
b: [ 0  2  4  6  8 10 12 14 16 18]
c: [0. 0. 0. 0. 0.]
d: [1. 1. 1. 1. 1.]
e: [0.  0.2 0.4 0.6 0.8 1. ]


## 3. Array properties

Useful array properties include:

- `.shape` — the dimensions of the array
- `.size` — the total number of values
- `.dtype` — the data type
- `.ndim` — the number of dimensions

In [4]:
values = np.array([5, 10, 15, 20])

print("Shape:", values.shape)
print("Size:", values.size)
print("Data type:", values.dtype)
print("Dimensions:", values.ndim)

Shape: (4,)
Size: 4
Data type: int64
Dimensions: 1


## 4. Basic indexing

Python indexing starts at zero.

| Expression | Meaning |
|---|---|
| `array[0]` | First item |
| `array[1]` | Second item |
| `array[-1]` | Last item |
| `array[-2]` | Second-last item |

In [5]:
values = np.array([10, 20, 30, 40, 50])

print("First:", values[0])
print("Second:", values[1])
print("Last:", values[-1])
print("Second-last:", values[-2])

First: 10
Second: 20
Last: 50
Second-last: 40


# Part B — Understanding the Colon Syntax

## 5. General slicing pattern

The general slicing pattern is:

```python
data[start:stop:step]
```

- `start` is included.
- `stop` is excluded.
- `step` controls how the index moves.
- Any part may be omitted.

For example, `data[2:6]` starts at index 2 and stops before index 6.

In [6]:
data = np.arange(10, 110, 10)
print("Complete array:", data)

print("data[2:6]:", data[2:6])

Complete array: [ 10  20  30  40  50  60  70  80  90 100]
data[2:6]: [30 40 50 60]


## 6. The meaning of `[:30]`

The expression:

```python
data[:30]
```

means:

> Start from the beginning and stop before index 30.

It returns at most the first 30 items. It does **not** mean values below 30.

In [7]:
data = np.arange(100)

first_30 = data[:30]

print(first_30)
print("Number of items:", len(first_30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Number of items: 30


Compare the following two expressions:

- `data[:30]` selects positions 0 to 29.
- `data[data < 30]` selects values that satisfy the condition `value < 30`.

They happen to produce the same result for `np.arange(100)`, but they mean different things.

In [13]:
data = np.array([100, 5, 60, 12, 200, 25, 70])
print("First 30 positions:", data[:30])
print("Values below 30:", data[data < 30])

First 30 positions: [100   5  60  12 200  25  70]
Values below 30: [ 5 12 25]


## 7. Common slicing patterns

In [14]:
data = np.arange(20)

print("Complete array: ", data)
print("First 5:        ", data[:5])
print("From index 5:   ", data[5:])
print("Index 5 to 9:   ", data[5:10])
print("Every 2nd item: ", data[::2])
print("Every 3rd item: ", data[::3])
print("Reversed:       ", data[::-1])
print("Last 5:         ", data[-5:])
print("Except last 5:  ", data[:-5])

Complete array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
First 5:         [0 1 2 3 4]
From index 5:    [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Index 5 to 9:    [5 6 7 8 9]
Every 2nd item:  [ 0  2  4  6  8 10 12 14 16 18]
Every 3rd item:  [ 0  3  6  9 12 15 18]
Reversed:        [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
Last 5:          [15 16 17 18 19]
Except last 5:   [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 8. Slicing diagram

For the array below:

```text
Values:  10  20  30  40  50  60
Index:    0   1   2   3   4   5
```

`array[1:4]` returns values at indices 1, 2, and 3. Index 4 is excluded.

In [15]:
array = np.array([10, 20, 30, 40, 50, 60])

print(array[1:4])

[20 30 40]


## 9. Exercise — NumPy slicing

Predict the output before running the cell.

In [ ]:
exercise_array = np.arange(0, 50, 5)
print(exercise_array)

# Uncomment one line at a time.
# print(exercise_array[:4])
# print(exercise_array[4:])
# print(exercise_array[2:7])
# print(exercise_array[::2])
# print(exercise_array[::-1])
# print(exercise_array[-3:])

[ 0  5 10 15 20 25 30 35 40 45]
[ 0 10 20 30 40]


## 10. Two-dimensional NumPy arrays

A two-dimensional array has rows and columns.

In [30]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

print(matrix)
print("Shape:", matrix.shape)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Shape: (4, 3)


For two-dimensional arrays, use:

```python
matrix[row_selection, column_selection]
```

The colon `:` by itself means “all items in this dimension”.

In [31]:
print("First row:")
print(matrix[0, :])

print("\nSecond column:")
print(matrix[:, 1])

print("\nFirst two rows:")
print(matrix[:2, :])

print("\nFirst two rows and first two columns:")
print(matrix[:2, :2])

print("\nRows 1 onward, columns 1 onward:")
print(matrix[1:, 1:])

First row:
[10 20 30]

Second column:
[ 20  50  80 110]

First two rows:
[[10 20 30]
 [40 50 60]]

First two rows and first two columns:
[[10 20]
 [40 50]]

Rows 1 onward, columns 1 onward:
[[ 50  60]
 [ 80  90]
 [110 120]]


## 11. NumPy calculations

NumPy calculations are applied to every value in the array.

In [32]:
numbers = np.array([1, 2, 3, 4, 5])

print("Add 10:", numbers + 10)
print("Multiply by 2:", numbers * 2)
print("Square:", numbers ** 2)
print("Mean:", numbers.mean())
print("Sum:", numbers.sum())
print("Minimum:", numbers.min())
print("Maximum:", numbers.max())

Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]
Mean: 3.0
Sum: 15
Minimum: 1
Maximum: 5


## 12. Boolean filtering

A condition produces an array of `True` and `False` values. This Boolean array may then be used to select matching values.

In [ ]:
scores = np.array([45, 72, 81, 39, 66, 90, 54])

print("Condition:")
print(scores >= 60)

print("\nScores of 60 or more:")
print(scores[scores >= 60])

# Part C — Basic pandas

## 13. Creating a Series

A pandas Series is a one-dimensional labelled collection.

In [33]:
temperatures = pd.Series([18.5, 19.2, 21.0, 20.4, 22.1])

print(temperatures)

0    18.5
1    19.2
2    21.0
3    20.4
4    22.1
dtype: float64


A custom index can be added.

In [34]:
temperatures = pd.Series(
    [18.5, 19.2, 21.0, 20.4, 22.1],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
)

print(temperatures)

Monday       18.5
Tuesday      19.2
Wednesday    21.0
Thursday     20.4
Friday       22.1
dtype: float64


## 14. Creating a DataFrame

A DataFrame is a table with rows and columns.

In [35]:
students = pd.DataFrame({
    "Name": ["Aisha", "Ben", "Chloe", "Daniel", "Elena", "Farah"],
    "Age": [19, 21, 20, 22, 19, 23],
    "Course": ["Computing", "Business", "Computing", "Design", "Business", "Computing"],
    "Score": [78, 65, 91, 58, 72, 84]
})

students

,Name,Age,Course,Score
0,Aisha,19,Computing,78
1,Ben,21,Business,65
2,Chloe,20,Computing,91
3,Daniel,22,Design,58
4,Elena,19,Business,72
5,Farah,23,Computing,84


## 15. Inspecting a DataFrame

Common methods and attributes include:

- `.head()` — first five rows
- `.head(10)` — first ten rows
- `.tail()` — last five rows
- `.shape` — number of rows and columns
- `.columns` — column names
- `.dtypes` — data type of each column
- `.info()` — summary of the DataFrame
- `.describe()` — descriptive statistics

In [37]:
print("Shape:", students.shape)
print("Columns:", students.columns.tolist())

display(students.head())
display(students.tail(2))
display(students.describe())

Shape: (6, 4)
Columns: ['Name', 'Age', 'Course', 'Score']


,Name,Age,Course,Score
0,Aisha,19,Computing,78
1,Ben,21,Business,65
2,Chloe,20,Computing,91
3,Daniel,22,Design,58
4,Elena,19,Business,72


,Name,Age,Course,Score
4,Elena,19,Business,72
5,Farah,23,Computing,84


,Age,Score
count,6.000000,6.000000
mean,20.666667,74.666667
std,1.632993,12.192894
min,19.000000,58.000000
25%,19.250000,66.750000
50%,20.500000,75.000000
75%,21.750000,82.500000
max,23.000000,91.000000


## 16. Selecting columns

A single column is normally selected with one pair of square brackets.

```python
students["Name"]
```

Multiple columns require a list of column names.

```python
students[["Name", "Score"]]
```

In [38]:
display(students["Name"])
display(students[["Name", "Score"]])

0     Aisha
1       Ben
2     Chloe
3    Daniel
4     Elena
5     Farah
Name: Name, dtype: str

,Name,Score
0,Aisha,78
1,Ben,65
2,Chloe,91
3,Daniel,58
4,Elena,72
5,Farah,84


## 17. Slicing DataFrame rows

The same colon syntax can select rows by position.

In [39]:
display(students[:3])     # First three rows
display(students[2:5])    # Rows at positions 2, 3, and 4
display(students[-2:])    # Last two rows

,Name,Age,Course,Score
0,Aisha,19,Computing,78
1,Ben,21,Business,65
2,Chloe,20,Computing,91


,Name,Age,Course,Score
2,Chloe,20,Computing,91
3,Daniel,22,Design,58
4,Elena,19,Business,72


,Name,Age,Course,Score
4,Elena,19,Business,72
5,Farah,23,Computing,84


For a larger DataFrame, `df[:30]` returns the first 30 rows.

In [40]:
large_df = pd.DataFrame({
    "Student_ID": np.arange(1, 101),
    "Score": np.random.default_rng(42).integers(40, 101, size=100)
})

display(large_df[:30])
print("Rows returned:", len(large_df[:30]))

,Student_ID,Score
0,1,45
1,2,87
2,3,79
3,4,66
4,5,66
5,6,92
6,7,45
7,8,82
8,9,52
9,10,45


Rows returned: 30


# Part D — `.loc[]` and `.iloc[]`

## 18. Selecting with `.iloc[]`

`.iloc[]` selects by integer position.

Its slicing behaviour follows normal Python rules: the stopping position is excluded.

In [ ]:
display(students.iloc[0])        # First row
display(students.iloc[:3])       # First three rows
display(students.iloc[1:4])      # Positions 1, 2, and 3
display(students.iloc[:, 0])     # All rows, first column
display(students.iloc[:3, :2])   # First three rows, first two columns

## 19. Selecting with `.loc[]`

`.loc[]` selects by row and column labels.

Important difference:

> Label-based slices with `.loc[]` normally include the stopping label.

In [ ]:
labelled_students = students.set_index("Name")
display(labelled_students)

In [ ]:
display(labelled_students.loc["Ben"])
display(labelled_students.loc["Ben":"Daniel"])
display(labelled_students.loc[:, ["Course", "Score"]])
display(labelled_students.loc["Ben":"Daniel", ["Course", "Score"]])

## 20. `.loc[]` compared with `.iloc[]`

| Method | Selects by | Stop included? |
|---|---|---|
| `.iloc[]` | Integer position | No |
| `.loc[]` | Label | Usually yes |

This difference is important when slicing rows.

In [ ]:
print("Using iloc:")
display(labelled_students.iloc[1:4])

print("Using loc:")
display(labelled_students.loc["Ben":"Daniel"])

# Part E — Filtering pandas data

## 21. Filtering with one condition

In [ ]:
high_scores = students[students["Score"] >= 70]
display(high_scores)

## 22. Filtering with multiple conditions

Use:

- `&` for AND
- `|` for OR
- `~` for NOT

Each condition should be enclosed in parentheses.

In [41]:
computing_high_scores = students[
    (students["Course"] == "Computing") &
    (students["Score"] >= 80)
]

display(computing_high_scores)

,Name,Age,Course,Score
2,Chloe,20,Computing,91
5,Farah,23,Computing,84


In [ ]:
selected_courses = students[
    (students["Course"] == "Computing") |
    (students["Course"] == "Design")
]

display(selected_courses)

## 23. Filtering with `.loc[]`

`.loc[]` can filter rows and select columns at the same time.

In [ ]:
display(
    students.loc[
        students["Score"] >= 70,
        ["Name", "Course", "Score"]
    ]
)

# Part F — Sorting and adding columns

## 24. Sorting

In [42]:
display(students.sort_values("Score"))
display(students.sort_values("Score", ascending=False))

,Name,Age,Course,Score
3,Daniel,22,Design,58
1,Ben,21,Business,65
4,Elena,19,Business,72
0,Aisha,19,Computing,78
5,Farah,23,Computing,84
2,Chloe,20,Computing,91


,Name,Age,Course,Score
2,Chloe,20,Computing,91
5,Farah,23,Computing,84
0,Aisha,19,Computing,78
4,Elena,19,Business,72
1,Ben,21,Business,65
3,Daniel,22,Design,58


## 25. Adding a calculated column

In [43]:
students_with_results = students.copy()

students_with_results["Passed"] = students_with_results["Score"] >= 60
students_with_results["Score_Percentage"] = students_with_results["Score"].astype(float)

display(students_with_results)

,Name,Age,Course,Score,Passed,Score_Percentage
0,Aisha,19,Computing,78,True,78.0
1,Ben,21,Business,65,True,65.0
2,Chloe,20,Computing,91,True,91.0
3,Daniel,22,Design,58,False,58.0
4,Elena,19,Business,72,True,72.0
5,Farah,23,Computing,84,True,84.0


## 26. Creating categories with `np.where()`

In [44]:
students_with_results["Result"] = np.where(
    students_with_results["Score"] >= 60,
    "Pass",
    "Fail"
)

display(students_with_results)

,Name,Age,Course,Score,Passed,Score_Percentage,Result
0,Aisha,19,Computing,78,True,78.0,Pass
1,Ben,21,Business,65,True,65.0,Pass
2,Chloe,20,Computing,91,True,91.0,Pass
3,Daniel,22,Design,58,False,58.0,Fail
4,Elena,19,Business,72,True,72.0,Pass
5,Farah,23,Computing,84,True,84.0,Pass


# Part G — Missing values

## 27. Finding and handling missing values

In [45]:
data_with_missing = pd.DataFrame({
    "Name": ["Aisha", "Ben", "Chloe", "Daniel"],
    "Score": [78, np.nan, 91, 58],
    "Attendance": [90, 85, np.nan, 75]
})

display(data_with_missing)

,Name,Score,Attendance
0,Aisha,78.0,90.0
1,Ben,NaN,85.0
2,Chloe,91.0,NaN
3,Daniel,58.0,75.0


In [46]:
print("Missing values by column:")
print(data_with_missing.isna().sum())

display(data_with_missing.dropna())
display(data_with_missing.fillna(0))

Missing values by column:
Name          0
Score         1
Attendance    1
dtype: int64


,Name,Score,Attendance
0,Aisha,78.0,90.0
3,Daniel,58.0,75.0


,Name,Score,Attendance
0,Aisha,78.0,90.0
1,Ben,0.0,85.0
2,Chloe,91.0,0.0
3,Daniel,58.0,75.0


# Part H — Student Practice

## Exercise 1 — Slicing

Using the array below:

1. Select the first 10 values.
2. Select values at positions 10 to 19.
3. Select every second value.
4. Select the last five values.
5. Reverse the array.

In [ ]:
practice = np.arange(1, 51)

# Write answers below.

# answer_1 =
# answer_2 =
# answer_3 =
# answer_4 =
# answer_5 =

## Exercise 2 — Two-dimensional slicing

Using the matrix below:

1. Select the first row.
2. Select the final column.
3. Select the first two rows and first three columns.
4. Select all rows except the first row.

In [ ]:
practice_matrix = np.arange(1, 21).reshape(4, 5)
print(practice_matrix)

# Write answers below.

## Exercise 3 — pandas selection

Using the `students` DataFrame:

1. Display the first four rows.
2. Select only the `Name` and `Score` columns.
3. Select rows at positions 2 to 4 using `.iloc[]`.
4. Display students with scores of at least 75.
5. Display Computing students with scores above 80.

In [ ]:
display(students)

# Write answers below.

## Exercise 4 — Challenge

From `large_df`:

1. Select the first 30 rows.
2. Select rows 30 to 39.
3. Select every tenth row.
4. Select the last 10 rows.
5. Find students whose score is at least 80.
6. Sort the results from highest to lowest score.

In [ ]:
display(large_df.head())

# Write answers below.

# Part I — Solutions

Students should attempt the exercises before opening this section.

In [ ]:
# Exercise 1 solutions

answer_1 = practice[:10]
answer_2 = practice[10:20]
answer_3 = practice[::2]
answer_4 = practice[-5:]
answer_5 = practice[::-1]

print("1:", answer_1)
print("2:", answer_2)
print("3:", answer_3)
print("4:", answer_4)
print("5:", answer_5)

In [ ]:
# Exercise 2 solutions

print("1. First row:")
print(practice_matrix[0, :])

print("\n2. Final column:")
print(practice_matrix[:, -1])

print("\n3. First two rows and first three columns:")
print(practice_matrix[:2, :3])

print("\n4. All rows except the first:")
print(practice_matrix[1:, :])

In [ ]:
# Exercise 3 solutions

display(students[:4])
display(students[["Name", "Score"]])
display(students.iloc[2:5])
display(students[students["Score"] >= 75])
display(students[(students["Course"] == "Computing") & (students["Score"] > 80)])

In [ ]:
# Exercise 4 solutions

display(large_df[:30])
display(large_df[30:40])
display(large_df[::10])
display(large_df[-10:])

high_results = large_df[large_df["Score"] >= 80]
display(high_results.sort_values("Score", ascending=False))

# Summary

The most important slicing patterns are:

| Syntax | Meaning |
|---|---|
| `data[:30]` | First 30 items |
| `data[30:]` | From position 30 to the end |
| `data[10:20]` | Positions 10 to 19 |
| `data[::2]` | Every second item |
| `data[::-1]` | Reverse the data |
| `data[-5:]` | Last five items |
| `matrix[:, 0]` | All rows from the first column |
| `matrix[0, :]` | All columns from the first row |
| `df.iloc[:30]` | First 30 rows by position |
| `df.loc[start:end]` | Rows from one label to another, usually including both labels |

Students should remember that the stopping position in normal Python and `.iloc[]` slices is excluded.